<?php require __DIR__.'/includes/app.php'; require __DIR__.'/includes/components.php'; $portrait=media_by_category('portrait',1)[0]??(media_items()[0]??[]); $items=$expertise['items']??[]; site_header('home'); ?>
<main>
<section class="editorial-hero shell hero-editorial"><div class="editorial-index">00 / JAHONGIRNEURO</div><div><div class="eyebrow">Neurosurgery · Farg‘ona</div><h1>Ilm.<br>Amaliyot.<br><em>Ishonch.</em></h1><p class="hero-intro"><?=h($doctor['bio']??'Professional neyroxirurgik faoliyat va bemorga individual yondashuv.')?></p><div class="actions"><a class="button primary" href="/contact.php">Qabulga yozilish ↗</a><a class="button" href="/portfolio.php">Portfolio ↗</a></div></div><div class="hero-side-note">PERSONAL MEDICAL<br>PORTFOLIO<br><span>2026 / FERGANA</span></div></section>
<section class="shell hero-media-stage"><figure class="portrait reveal-premium hover-trigger"><div class="premium-number" aria-hidden="true">01</div><?php if($portrait): ?><img src="<?=h(media_src($portrait))?>" alt="<?=h($portrait['title']??'Jahongir Neuro')?>" fetchpriority="high"><?php endif; ?><figcaption class="portrait-badge"><?=h($doctor['title']??'Vrach-neyroxirurg')?> · <?=h($doctor['experience']??'')?></figcaption></figure><div class="hero-media-caption"><span>01 / IDENTITY</span><strong><?=h($doctor['name']??'Jahongir Neuro')?></strong><small>Neurosurgery · Professional practice</small></div></section>
<section class="shell stats"><?php foreach(($doctor['stats']??[]) as $stat): ?><div class="stat reveal-premium"><strong><?=h($stat['value']??'')?></strong><span><?=h($stat['label']??'')?></span></div><?php endforeach; ?></section>
<section class="section shell"><div class="editorial-split"><div class="editorial-label">02 / EXPERTISE</div><div class="statement"><span>“</span><p>Murakkab holatlar uchun <em>aniq fikr</em>, individual yondashuv va mas’uliyatli qaror.</p></div></div><div class="premium-bento"><?php foreach(array_slice($items,0,6) as $i=>$item): ?><article class="glass-card hover-trigger reveal-premium"><span class="premium-number" aria-hidden="true"><?=str_pad((string)($i+1),2,'0',STR_PAD_LEFT)?></span><div><span class="number">0<?=($i+1)?></span><h3><?=h($item['title']??'')?></h3><p><?=h($item['description']??'')?></p></div><a class="premium-glass-button" href="/services.php">Batafsil ↗</a></article><?php endforeach; ?></div></section>
<section class="section shell"><div class="clinical-stage reveal-premium"><div class="eyebrow">03 / PHILOSOPHY</div><h2>Shifokorlik —<br><em>faqat texnika emas.</em></h2><p><?=h($about['philosophy']??$about['bio']??'Bilim, aniqlik va insoniy yondashuv.')?></p><a class="button" href="/about.php">To‘liq profil ↗</a></div></section>
<section class="section shell"><div class="section-head"><div><div class="eyebrow">04 / EVIDENCE</div><h2>Real faoliyat.<br>Real media.</h2></div><p>Professional uchrashuvlar, klinik faoliyat va portretlardan tuzilgan original media arxivi.</p></div><div class="portfolio-wall"><?php foreach(array_slice(media_items(),0,5) as $i=>$item): $item['_class']='reveal-premium hover-trigger'; echo media_card($item,$i); endforeach; ?></div><div style="margin-top:28px"><a class="button" href="/portfolio.php">To‘liq arxiv ↗</a></div></section>
<section class="section shell"><div class="final-cta reveal-premium"><span>05 / CONNECTION</span><h2>Professional aloqa<br><em>shu yerdan boshlanadi.</em></h2><a class="button primary" href="/contact.php">Bog‘lanish ↗</a></div></section>
</main><?php site_footer(); ?>