<?php
declare(strict_types=1);

function site_media(): array {
    static $items = null;
    if ($items !== null) return $items;
    $file = __DIR__ . '/../data/media.json';
    $data = is_file($file) ? json_decode((string) file_get_contents($file), true) : [];
    $items = is_array($data['items'] ?? null) ? $data['items'] : [];
    return $items;
}
function media_pick(array $categories = [], int $limit = 8, int $offset = 0): array {
    $items = site_media();
    if ($categories) $items = array_values(array_filter($items, static fn($x) => in_array((string)($x['category'] ?? ''), $categories, true)));
    return array_slice($items, $offset, $limit);
}
function media_url(array $item): string { return '/' . ltrim((string)($item['path'] ?? ''), '/'); }
function media_ext(array $item): string { return strtolower(pathinfo((string)($item['name'] ?? ''), PATHINFO_EXTENSION)); }
function media_card(array $item, int $index = 0, string $class = ''): string {
    $url = htmlspecialchars(media_url($item), ENT_QUOTES, 'UTF-8');
    $title = htmlspecialchars((string)($item['title'] ?? 'Professional media'), ENT_QUOTES, 'UTF-8');
    $name = htmlspecialchars((string)($item['name'] ?? ''), ENT_QUOTES, 'UTF-8');
    $cat = htmlspecialchars((string)($item['category'] ?? 'professional'), ENT_QUOTES, 'UTF-8');
    $ext = media_ext($item); $isVideo = ($item['type'] ?? '') === 'video' || $ext === 'mov'; $isHeic = $ext === 'heic';
    if ($isVideo) $body = '<video controls preload="metadata" playsinline><source src="'.$url.'" type="video/quicktime"></video>';
    elseif ($isHeic) $body = '<div class="media-heic-wrap"><img class="media-heic-preview" data-heic-src="'.$url.'" alt="'.$title.' — Jahongir Neuro" loading="lazy" decoding="async"><div class="media-heic-fallback"><span>HEIC</span><strong>'.$name.'</strong><small>Preview yuklanmoqda…</small><a href="'.$url.'" target="_blank" rel="noopener">Original faylni ochish ↗</a></div></div>';
    else $body = '<img src="'.$url.'" loading="lazy" decoding="async" alt="'.$title.' — Jahongir Neuro">';
    return '<article class="media-card '.htmlspecialchars($class, ENT_QUOTES, 'UTF-8').'" data-category="'.$cat.'"><div class="media-visual">'.$body.'</div><div class="media-caption"><span>'.$cat.'</span><strong>'.str_pad((string)($index + 1), 2, '0', STR_PAD_LEFT).' · '.$title.'</strong></div></article>';
}
function media_styles(): string {
return <<<'HTML'
<script src="https://cdn.jsdelivr.net/npm/heic2any@0.0.4/dist/heic2any.min.js" defer></script>
<style>
.media-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.media-card{background:#fff;border:1px solid rgba(16,22,19,.08);border-radius:26px;overflow:hidden;box-shadow:0 14px 45px rgba(15,92,77,.06);transition:transform .45s cubic-bezier(.22,1,.36,1),box-shadow .45s ease}.media-card:hover{transform:translateY(-6px);box-shadow:0 28px 70px rgba(15,92,77,.13)}.media-visual{background:linear-gradient(145deg,#e3eee9,#c8d9d3);min-height:250px;overflow:hidden}.media-visual img,.media-visual video{width:100%;height:100%;min-height:250px;max-height:520px;display:block;object-fit:cover}.media-visual video{background:#101613}.media-heic-wrap{position:relative;min-height:250px;height:100%;background:linear-gradient(145deg,#e3eee9,#c8d9d3)}.media-heic-preview{opacity:0;position:absolute!important;inset:0;width:100%!important;height:100%!important;object-fit:cover;transition:opacity .35s ease}.media-heic-wrap.ready .media-heic-preview{opacity:1}.media-heic-fallback{min-height:250px;padding:26px;display:flex;flex-direction:column;justify-content:flex-end;color:#174f45}.media-heic-wrap.ready .media-heic-fallback{display:none}.media-heic-fallback span{font-size:10px;font-weight:850;letter-spacing:.16em;color:#0f5c4d}.media-heic-fallback strong{font-size:18px;margin-top:10px;word-break:break-all}.media-heic-fallback small{margin-top:12px;color:#68756f}.media-heic-fallback a{margin-top:14px;color:#0f5c4d;font-size:11px;font-weight:800}.media-caption{padding:14px 16px 17px}.media-caption span{display:block;font-size:9px;text-transform:uppercase;letter-spacing:.14em;color:#0f5c4d;font-weight:850}.media-caption strong{display:block;margin-top:7px;font-size:13px;line-height:1.35}
.menu-toggle{display:none;position:relative;width:42px;height:42px;flex:0 0 42px;border:0;border-radius:50%;background:#0f5c4d;color:#fff;cursor:pointer;align-items:center;justify-content:center;padding:0;z-index:101;box-shadow:0 8px 22px rgba(15,92,77,.18)}.menu-toggle span,.menu-toggle span:before,.menu-toggle span:after{display:block;width:17px;height:1.5px;background:currentColor;border-radius:3px;transition:transform .25s ease,opacity .2s ease}.menu-toggle span{position:relative}.menu-toggle span:before,.menu-toggle span:after{content:"";position:absolute;left:0}.menu-toggle span:before{top:-5px}.menu-toggle span:after{top:5px}.menu-toggle[aria-expanded="true"] span{background:transparent}.menu-toggle[aria-expanded="true"] span:before{transform:translateY(5px) rotate(45deg)}.menu-toggle[aria-expanded="true"] span:after{transform:translateY(-5px) rotate(-45deg)}
.mobile-nav{position:fixed;z-index:100;top:76px;left:12px;right:12px;padding:10px;display:grid;gap:5px;background:rgba(255,255,255,.94);border:1px solid rgba(255,255,255,.98);border-radius:25px;backdrop-filter:blur(28px);-webkit-backdrop-filter:blur(28px);box-shadow:0 24px 70px rgba(15,92,77,.18);opacity:0;visibility:hidden;transform:translateY(-10px) scale(.98);transform-origin:top right;transition:opacity .22s ease,transform .28s cubic-bezier(.22,1,.36,1),visibility .22s ease}.mobile-nav.open{opacity:1;visibility:visible;transform:none}.mobile-nav a{display:flex!important;align-items:center;min-height:50px;padding:0 16px!important;border-radius:16px!important;color:#50605a!important;font-size:14px!important;font-weight:750;background:transparent}.mobile-nav a:hover,.mobile-nav a.active{background:#e3eeea!important;color:#174f45!important}.mobile-nav a.cta{background:#0f5c4d!important;color:#fff!important;justify-content:center;margin-top:3px}.nav-backdrop{position:fixed;inset:0;z-index:90;background:rgba(15,22,19,.12);backdrop-filter:blur(2px);-webkit-backdrop-filter:blur(2px);opacity:0;visibility:hidden;transition:opacity .2s ease,visibility .2s ease}.nav-backdrop.open{opacity:1;visibility:visible}body.menu-open{overflow:hidden}
/* DESIGN SYSTEM V2 — inspired by the supplied premium glass direction, rebuilt for a medical brand. */
:root{--v2-bg:#f7f9f7;--v2-paper:rgba(255,255,255,.72);--v2-ink:#0c1713;--v2-muted:#64716b;--v2-green:#0f5c4d;--v2-deep:#174f45;--v2-soft:#e3eeea;--v2-line:rgba(12,23,19,.085);--v2-glow:rgba(15,92,77,.16)}
html{scroll-behavior:smooth}body{background:radial-gradient(circle at 12% 12%,rgba(227,238,234,.9) 0,transparent 27%),radial-gradient(circle at 88% 18%,rgba(15,92,77,.06) 0,transparent 24%),var(--v2-bg)!important;color:var(--v2-ink)!important;overflow-x:hidden}body:before{content:"";position:fixed;inset:-20%;pointer-events:none;z-index:-1;background:radial-gradient(circle at 50% 0,rgba(255,255,255,.95),transparent 42%);filter:blur(25px)}
.nav{background:rgba(255,255,255,.68)!important;border-color:rgba(255,255,255,.9)!important;box-shadow:0 18px 60px rgba(15,92,77,.10),inset 0 1px 0 rgba(255,255,255,.95)!important;backdrop-filter:blur(30px) saturate(150%)!important;-webkit-backdrop-filter:blur(30px) saturate(150%)!important;transition:transform .35s ease,box-shadow .35s ease!important}.nav:hover{box-shadow:0 24px 80px rgba(15,92,77,.14),inset 0 1px 0 #fff!important}.brand{font-size:17px!important}.links a{transition:background .25s ease,color .25s ease,transform .25s ease!important}.links a:hover{transform:translateY(-1px)!important}.links .cta,.cta a,.button.primary,.submit{box-shadow:0 12px 28px rgba(15,92,77,.18)!important}
.hero{position:relative}.hero:before{content:"";position:absolute;width:520px;height:520px;right:-180px;top:50px;border-radius:50%;background:radial-gradient(circle,rgba(15,92,77,.12),transparent 68%);filter:blur(35px);pointer-events:none;z-index:-1}.hero h1{font-weight:900!important;text-wrap:balance;text-shadow:0 2px 0 rgba(255,255,255,.65)!important}.hero p{color:var(--v2-muted)!important}.eyebrow{font-weight:900!important;color:var(--v2-green)!important}.button{background:rgba(255,255,255,.62)!important;border-color:rgba(255,255,255,.95)!important;box-shadow:0 8px 25px rgba(12,23,19,.05)!important;backdrop-filter:blur(12px)!important;-webkit-backdrop-filter:blur(12px)!important;transition:transform .3s cubic-bezier(.22,1,.36,1),box-shadow .3s ease!important}.button:hover{transform:translateY(-3px)!important;box-shadow:0 18px 38px rgba(15,92,77,.13)!important}.button.primary{background:linear-gradient(135deg,#0f5c4d,#174f45)!important;border-color:#0f5c4d!important}
.portrait{border:1px solid rgba(255,255,255,.9)!important;box-shadow:0 40px 100px rgba(15,92,77,.16),inset 0 1px 0 #fff!important;position:relative}.portrait:after{content:"";position:absolute;inset:0;pointer-events:none;background:linear-gradient(135deg,rgba(255,255,255,.24),transparent 36%,rgba(15,92,77,.08));mix-blend-mode:screen}.portrait img{transition:transform 1s cubic-bezier(.22,1,.36,1),filter .8s ease!important}.portrait:hover img{transform:scale(1.025)!important;filter:saturate(1.03)!important}
.stats{border-top-color:var(--v2-line)!important}.stat strong{font-weight:900!important;letter-spacing:-.04em}.stat span{color:#7b8781!important}
.section,.media-section{position:relative}.section:before,.media-section:before{content:"";position:absolute;left:50%;top:0;width:min(100%,900px);height:1px;transform:translateX(-50%);background:linear-gradient(90deg,transparent,rgba(15,92,77,.16),transparent);pointer-events:none}.head h2,.media-head h2,.hero h1,.dark h2,.contact h2,.archive h2,.cta h2{font-weight:900!important;text-wrap:balance}.exp,.card{background:rgba(255,255,255,.62)!important;border-color:rgba(255,255,255,.92)!important;box-shadow:0 16px 50px rgba(12,23,19,.055),inset 0 1px 0 rgba(255,255,255,.96)!important;backdrop-filter:blur(18px)!important;-webkit-backdrop-filter:blur(18px)!important;transition:transform .45s cubic-bezier(.22,1,.36,1),box-shadow .45s ease,border-color .35s ease!important}.exp:hover,.card:hover{transform:translateY(-7px)!important;box-shadow:0 28px 70px rgba(15,92,77,.12),inset 0 1px 0 #fff!important;border-color:rgba(15,92,77,.16)!important}.exp h3{font-weight:900!important}.exp p,.card p{color:var(--v2-muted)!important}
.dark,.contact,.archive,.cta{box-shadow:0 35px 95px rgba(15,92,77,.17),inset 0 1px 0 rgba(255,255,255,.12)!important;position:relative;overflow:hidden}.dark:before,.contact:before,.archive:before,.cta:before{content:"";position:absolute;width:460px;height:460px;right:-180px;top:-210px;border-radius:50%;background:radial-gradient(circle,rgba(255,255,255,.16),transparent 68%);pointer-events:none}.dark>* ,.contact>* ,.archive>* ,.cta>*{position:relative;z-index:1}.pub{transition:transform .3s ease,background .3s ease!important}.pub:hover{transform:translateX(5px)!important;background:rgba(255,255,255,.08)!important}.contact a,.cta a{transition:transform .3s cubic-bezier(.22,1,.36,1),box-shadow .3s ease!important}.contact a:hover,.cta a:hover{transform:translateY(-3px)!important;box-shadow:0 16px 35px rgba(0,0,0,.16)!important}
.media-card{background:rgba(255,255,255,.64)!important;border-color:rgba(255,255,255,.94)!important;box-shadow:0 16px 48px rgba(12,23,19,.06),inset 0 1px 0 #fff!important;backdrop-filter:blur(15px)!important;-webkit-backdrop-filter:blur(15px)!important;transition:transform .5s cubic-bezier(.22,1,.36,1),box-shadow .5s ease,border-color .4s ease!important}.media-card:hover{transform:translateY(-9px) scale(1.008)!important;box-shadow:0 32px 80px rgba(15,92,77,.15),inset 0 1px 0 #fff!important;border-color:rgba(15,92,77,.17)!important}.media-visual{background:linear-gradient(145deg,#e7f0ed,#c7d9d2)!important}.media-visual img{transition:transform .8s cubic-bezier(.22,1,.36,1),filter .5s ease!important}.media-card:hover .media-visual img{transform:scale(1.035)!important;filter:saturate(1.04)!important}.media-caption{background:rgba(255,255,255,.28)!important}.media-caption strong{font-weight:800!important}
.filters{background:rgba(255,255,255,.68)!important;border-color:rgba(255,255,255,.92)!important;box-shadow:0 18px 55px rgba(15,92,77,.09)!important}.filter{transition:transform .25s ease,background .25s ease!important}.filter:hover{transform:translateY(-1px)!important}.filter.active{box-shadow:0 8px 22px rgba(15,92,77,.18)!important}
.field input,.field textarea{background:rgba(248,250,249,.78)!important;border-color:rgba(12,23,19,.10)!important;transition:border-color .25s ease,box-shadow .25s ease,background .25s ease!important}.field input:focus,.field textarea:focus{background:#fff!important;border-color:var(--v2-green)!important;box-shadow:0 0 0 5px rgba(15,92,77,.08),0 10px 30px rgba(15,92,77,.07)!important}.submit{transition:transform .25s ease,box-shadow .25s ease!important}.submit:hover{transform:translateY(-2px)!important;box-shadow:0 18px 38px rgba(15,92,77,.24)!important}
.row{transition:padding-left .35s ease,background .35s ease!important}.row:hover{padding-left:10px!important}.arrow{transition:transform .3s ease,background .3s ease,color .3s ease!important}.service:hover .arrow{transform:rotate(45deg)!important;background:var(--v2-soft)!important}.footer{color:#7b8781!important}
/* supplied-file interaction language: subtle cursor + pointer spotlight on desktop only */
.v2-cursor-dot,.v2-cursor-ring,.v2-spotlight{position:fixed;pointer-events:none;z-index:9999}.v2-cursor-dot{width:7px;height:7px;border-radius:50%;background:#0f5c4d;transform:translate(-50%,-50%);box-shadow:0 0 16px rgba(15,92,77,.45)}.v2-cursor-ring{width:34px;height:34px;border:1px solid rgba(15,92,77,.45);border-radius:50%;transform:translate(-50%,-50%);transition:width .25s ease,height .25s ease,background .25s ease,border-color .25s ease}.v2-cursor-ring.hover{width:54px;height:54px;background:rgba(15,92,77,.07);border-color:transparent}.v2-spotlight{width:700px;height:700px;border-radius:50%;background:radial-gradient(circle,rgba(15,92,77,.08),transparent 67%);filter:blur(30px);transform:translate(-50%,-50%);z-index:0;opacity:.75}
@media(max-width:900px){.media-grid{grid-template-columns:repeat(2,1fr)}.hero{min-height:auto!important;grid-template-columns:1fr!important;gap:34px!important;padding-top:120px!important;padding-bottom:65px!important}.hero h1{font-size:clamp(56px,12vw,92px)!important;max-width:100%!important}.hero p{font-size:18px!important;max-width:680px!important}.portrait{height:min(72svh,620px)!important;min-height:430px!important;width:100%!important}.head{grid-template-columns:1fr!important;gap:22px!important}.expertise{grid-template-columns:repeat(2,1fr)!important}.dark{grid-template-columns:1fr!important}.contact{display:block!important}.contact a{display:inline-flex;margin-top:24px}.layout{grid-template-columns:1fr!important}.service{grid-template-columns:40px 1fr 42px!important}.service>div:nth-child(3){grid-column:2!important}.archive{grid-template-columns:1fr!important}}
@media(max-width:560px){.media-grid{grid-template-columns:1fr}.wrap{width:calc(100% - 24px)!important}.nav{top:9px!important;width:calc(100% - 18px)!important;height:58px!important;padding:7px 8px 7px 15px!important}.menu-toggle{display:flex}.nav .links{display:none!important}.mobile-nav{top:76px}.hero{padding-top:105px!important;padding-bottom:58px!important;min-height:auto!important;gap:30px!important}.hero h1{font-size:clamp(50px,15.5vw,72px)!important;line-height:.86!important;letter-spacing:-.075em!important;margin:17px 0 23px!important;overflow-wrap:anywhere}.hero p{font-size:17px!important;line-height:1.5!important}.actions{gap:8px!important;margin-top:24px!important}.button{padding:13px 17px!important;font-size:12px!important}.portrait{height:66svh!important;min-height:420px!important;max-height:590px!important;border-radius:27px!important}.portrait-note{font-size:10px!important}.stats{grid-template-columns:repeat(2,1fr)!important;gap:14px!important;margin-top:38px!important}.stat strong{font-size:21px!important}.section,.media-section{padding:76px 0!important}.head{margin-bottom:36px!important}.head h2,.media-head h2{font-size:clamp(45px,13vw,64px)!important}.head p,.media-head p{font-size:13px!important}.expertise{grid-template-columns:1fr!important}.exp{min-height:240px!important;border-radius:23px!important;padding:23px!important}.exp h3{font-size:25px!important}.dark,.contact,.archive,.cta{border-radius:27px!important;padding:31px 24px!important}.dark h2,.contact h2,.archive h2,.cta h2{font-size:clamp(42px,12.5vw,58px)!important}.pub{padding:20px!important}.pub h3{font-size:18px!important}.media-section{padding-top:72px!important}.media-card{border-radius:22px!important}.media-visual,.media-visual img,.media-visual video,.media-heic-wrap,.media-heic-fallback{min-height:260px!important}.media-caption{padding:13px 14px 16px!important}.service{grid-template-columns:27px 1fr 36px!important;gap:10px!important;padding:28px 0!important}.service h2{font-size:29px!important}.arrow{width:36px!important;height:36px!important}.row{grid-template-columns:1fr!important;gap:8px!important}.fields{grid-template-columns:1fr!important}.field.full{grid-column:auto!important}.card{padding:25px!important;border-radius:24px!important}.info{min-height:auto!important}.footer{display:block!important}.footer span{display:block!important;margin-top:8px!important}}
@media(max-width:420px){.mobile-nav{left:9px;right:9px;top:72px;border-radius:22px}.menu-toggle{width:40px;height:40px;flex-basis:40px}.wrap{width:calc(100% - 20px)!important}.hero h1{font-size:52px!important}.portrait{height:58svh!important;min-height:390px!important}.actions .button{width:100%;justify-content:center}.stats{gap:10px!important}.stat strong{font-size:19px!important}.stat span{font-size:9px!important}.dark,.contact,.archive{padding:27px 20px!important}}
@media(min-width:851px){.mobile-nav,.nav-backdrop{display:none!important}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}.media-card,.exp,.card,.button,.submit{transition:none!important}.v2-cursor-dot,.v2-cursor-ring,.v2-spotlight{display:none!important}}
@media(pointer:coarse){.v2-cursor-dot,.v2-cursor-ring,.v2-spotlight{display:none!important}}
</style>
<script>
(function(){function initMobileNav(){const nav=document.querySelector('.nav');if(!nav||nav.dataset.mobileReady==='1')return;const links=nav.querySelector('.links');if(!links)return;nav.dataset.mobileReady='1';const toggle=document.createElement('button');toggle.className='menu-toggle';toggle.type='button';toggle.setAttribute('aria-label','Menyuni ochish');toggle.setAttribute('aria-expanded','false');toggle.innerHTML='<span></span>';nav.appendChild(toggle);const drawer=document.createElement('div');drawer.className='mobile-nav';drawer.setAttribute('aria-hidden','true');[...links.querySelectorAll('a')].forEach(source=>drawer.appendChild(source.cloneNode(true)));const backdrop=document.createElement('div');backdrop.className='nav-backdrop';document.body.append(drawer,backdrop);const close=()=>{drawer.classList.remove('open');backdrop.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Menyuni ochish');drawer.setAttribute('aria-hidden','true');document.body.classList.remove('menu-open')};const open=()=>{drawer.classList.add('open');backdrop.classList.add('open');toggle.setAttribute('aria-expanded','true');toggle.setAttribute('aria-label','Menyuni yopish');drawer.setAttribute('aria-hidden','false');document.body.classList.add('menu-open')};toggle.addEventListener('click',()=>toggle.getAttribute('aria-expanded')==='true'?close():open());backdrop.addEventListener('click',close);drawer.addEventListener('click',e=>{if(e.target.closest('a'))close()});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});window.addEventListener('resize',()=>{if(window.innerWidth>850)close()})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initMobileNav,{once:true});else initMobileNav()})();
(function(){if(window.matchMedia('(pointer:coarse)').matches||window.matchMedia('(prefers-reduced-motion:reduce)').matches)return;const dot=document.createElement('div'),ring=document.createElement('div'),spot=document.createElement('div');dot.className='v2-cursor-dot';ring.className='v2-cursor-ring';spot.className='v2-spotlight';document.body.append(spot,dot,ring);let x=-100,y=-100,rx=-100,ry=-100,sx=-100,sy=-100;window.addEventListener('mousemove',e=>{x=e.clientX;y=e.clientY;dot.style.left=x+'px';dot.style.top=y+'px'});function tick(){rx+=(x-rx)*.18;ry+=(y-ry)*.18;sx+=(x-sx)*.055;sy+=(y-sy)*.055;ring.style.left=rx+'px';ring.style.top=ry+'px';spot.style.left=sx+'px';spot.style.top=sy+'px';requestAnimationFrame(tick)}tick();document.addEventListener('mouseover',e=>{if(e.target.closest('a,button,.exp,.card,.media-card,.service,.pub'))ring.classList.add('hover')});document.addEventListener('mouseout',e=>{if(e.target.closest('a,button,.exp,.card,.media-card,.service,.pub'))ring.classList.remove('hover')})})();
(function(){const boot=()=>{const nodes=[...document.querySelectorAll('img[data-heic-src]')];if(!nodes.length)return;const convert=async img=>{try{if(typeof window.heic2any!=='function')throw new Error('converter unavailable');const res=await fetch(img.dataset.heicSrc,{credentials:'same-origin',cache:'force-cache'});if(!res.ok)throw new Error('HTTP '+res.status);const blob=await res.blob();const out=await window.heic2any({blob,type:'image/jpeg',quality:.88});const result=Array.isArray(out)?out[0]:out;img.src=URL.createObjectURL(result);img.closest('.media-heic-wrap')?.classList.add('ready')}catch(err){img.closest('.media-heic-wrap')?.classList.add('failed')}};const io='IntersectionObserver'in window?new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){io.unobserve(e.target);convert(e.target)}}),{rootMargin:'300px'}):null;nodes.forEach(n=>io?io.observe(n):convert(n))};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.addEventListener('load',()=>setTimeout(boot,250),{once:true})})();
</script>
HTML;
}
